apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: onboarding
  description: A workflow for onboarding applications to OCP cluster
  annotations:
    backstage.io/kubernetes-namespace: sonataflow-infra
    backstage.io/kubernetes-id: onboarding-ci
    janus-idp.io/tekton: onboarding
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ch007m/onboarding
spec:
  type: workflow-project
  system: system:default/quarkus-demo
  lifecycle: development
  owner: user:guest